build:
	npx tsc
	npx esbuild dist/main.js --bundle --platform=node --target=node20 --format=esm --minify --outfile=dist/index.js --allow-overwrite
	npx esbuild dist/post.js --bundle --platform=node --target=node20 --format=esm --minify --outfile=dist/post.js --allow-overwrite

all: build
